### ISSUE TITLE
Map widget captures scroll

### ISSUE THREAD

**Issue by jacobtomlinson** [volny/stylish-portfolio-jekyll#1]
Love the theme, looks great.

Slight problem with it is when scrolling down the page and the mouse enters the map widget the map starts to zoom and the scrolling stops. 

Perhaps it would be good to only enable the zoom when the user clicks on the map, or disable the scroll zoom altogether?

**Comment by volny** [comment]
Agreed, the map behavior can be annoying. Will fix.

**Comment by volny** [comment]
@jacobtomlinson fixed. feedback appreciated!
