### ISSUE TITLE
an error on line 12 of `_config.yml` file

### ISSUE THREAD

**Issue by AbhinayMe** [volny/stylish-portfolio-jekyll#2]
Getting an email alert from github pages as 

The page build failed with the following error:

You have an error on line 12 of your `_config.yml` file. For more information, see https://help.github.com/articles/page-build-failed-config-file-error.

**Comment by volny** [comment]
I seems like you don't have your code up on Github (or I didn't find it) so it's hard for me to tell from a distance what went wrong. The line `owner:` expects a string, so if the value you provided is ambiguous try putting quotes around it or use `>`, like in the `description:` in the example. If you provide your `_config.yaml` I can take a closer look.

**Comment by AbhinayMe** [comment]
Sorry I have tried to attach files but something went wrong with github uploader. Please try this link. Thank you. [Link Masked]

**Comment by volny** [comment]
try an empty space after `:`

**Comment by AbhinayMe** [comment]
Yeah... I missed it. That worked like charm now. Thank you.
